notifications:
  email: false
branches:
  only:
    - develop
language: android
android:
  components:
    - build-tools-20.0.0
before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - git clone https://github.com/tilal6991/Relay.git libraries/relay -b develop
  - git clone https://github.com/tilal6991/Bus.git libraries/bus -b develop
script: ./gradlew assembleSimpleDebug && ./gradlew testSimpleDebug